# Dockerfile para Django

# Usar imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar requirements.txt e instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do Django (e do Streamlit, já que está tudo na raiz)
COPY . .

# Expor a porta para o Django
EXPOSE 8000

# Rodar o Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
