version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - .:/app  # Monta o diretório raiz no contêiner

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  # Inclua a chave de API, se necessário
    volumes:
      - .:/app  # Monta o diretório raiz no contêiner
