# Dockerfile para Streamlit

# Usar imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar requirements.txt e instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código (incluindo o script do Streamlit)
COPY . .

# Expor a porta para o Streamlit
EXPOSE 8501

# Rodar o Streamlit
CMD ["streamlit", "run", "model.py", "--server.port=8501", "--server.address=0.0.0.0"]
